---
title: "Ejercicio Markdown"
author: "Eduardo Contreras"
date: "22 de agosto de 2016"
output: html_document
---

Encabezado
# **Primer Nivel**

x<-c(1+2i,5,3+9i,-4-5i)
x
class(x)

x<- 10:0
x
class(x)

x<- c("a","b","c","d")
x
class(x)
## *Segundo Nivel*

###Tercer Nivel

Lista
* 1er elemento

* 2do elemento

* 3er elemento
x<- ""
x
class(X)


#Mezcla de objetos en un vector
y<- c(1.7,"a") #caracter
y 
class(y)

y<- (TRUE,2)  #num??rico
y
class(y)

y<- c("a", TRUE) #caracter

y<- c(TRUE, 10L,8.5, 1+1i, "a")
y
class(y)

y<- c(TRUE, 10L,8.5, 1+1i)
y
class(y)

# Orden de coacci??n/cohersi??n expl??cita
#1 character
#2 complex
#3 numeric
#4 integer
#5 logical

#coerci??n explicita
z<- 0:6
class(z)
as.numeric(Z)
as.logical(Z)

z<- c(1+2i,3+4i,8,0+3i,0)
as.logical(z)



z<- c("programaci??n", "Actuarial, "III")
as.numeric(z)
as.logical






#LISTAS
x <- list(1,"a", TRUE, 1+4i)
x

#Lista (es como un vector... pero de vectores y c/u tiene su propia clase)

x<- list(1,"a", true, 1+4i, 1:100)
x


#MATRICES
m<- matrix(nrow= 2, ncol= 3)
m
dim(m)
attributes(m)
#cambio de dimensiones de 2x3 a 3x2
dim(m)<- c(3,2)



m<- matrix(1:6,3,2)
m

m<- matrix(1:6,3,3,TRUE)
m
class (m)
str(m)

#dim(m)<- c(2,5) #esto producira error

x<- c(1,2,3)
y<- c("a","b","c")
z<- c(x,y)
z

dim(m) <-c(2,3)
m1 <- rbind(m,x)
m1

m2 <- cbind(m,x)
m2

rbind(m1,y)
cbind(m2,y)



#Data Frames
x<- data.frame(Erik=1:4, Lori= c(T,T,F,F))
row.names(x) <- c("Primero", "Segundo", "Tercero", "Cuarto")
x
nrow(x)
ncol(col)
attributes(x)
names(x) <- c("Yarely", "Karen")
x

#Los nombres no son exclusivos de los data frames
x<- 1:3
names(x) 
#Null
names(x) <-c("Hugo", "Paco", "Luis")
x


x<- list(a=1:10, b=100:91,c=51:60)
x

names(x)<- c ("Seq1", "SEQ2", "SEQ3")
x

m<- matrix(1:4, 2,2)
m
attributes(m)
dimnames(m)<- list(c("fil1", "fil2"),c("col1","col2"))
m



r<- matrix(nrow= 5, ncol= 6)
r
dimnames(r)<-list(c("1","2","3","4","5"),c("A","B","C", "D", "E", "F"))
r

getwd
setwd("~/Desktop/Programacion III/Programacion_Actuaria_lII_-OT16")
data <- read.csv("Table.csv")
data <- read.table("Table.csv", T, ",")
#clase 3 septiembre
args(read.table)
#leer 100 filas
data<- read.table("Table.csv",T, "", nrows=100)
classes <- sapply(data,class)


view
data

#USO DE dput y dget
y<- data.frame(a=1,b= "a")
dput(y)
dput(y,file= "y.R")

nueva.y<-dget("y.R")
y
nueva.y

x<- "Programaci??n Actuarial III"
y<- data.frame(a=1,b= "a")
dump(c("x","y"),file= "data.R")
rm(x,y)
source("data.R")


x<- head(airquality)
dput(x, file= "airq.R")
x

#Creamos un vector
x <- c("a","b", "c", "d", "e")
x
#extraemos elementos con []
x[1]
x[2]
#secuencia de elementos
x[1:4]
#elementos con una restriccion
x[x>"b"]
# se puede obtener un vector l??gico
u<- x == "c"
u
x[u]



#Cremos una lista
x<- list(foo=1:4, bar=0.6)
#Exraemos el primer elemento de la lista,  este elemento es una lista que contiene una secuencia
x[1]

#extraemos nuevamente el primer elemento de la lista, ahora el elemento es la secuencia en si
x[[1]]
#extraemos un elemeto por nombre
x$bar
x[["bar"]]
x["bar"]



#puedes extraer elementos de los elementos 
x<- list(a= list(10,12,14), b=list(3.14,2.81))
x[[c(1,3)]]
x[[1]][[3]]
x[[c(2,1)]]

x<- matrix(1:6,2,3)
x

x[1,2]
x[2,1]
x[1,]
x[,2]

#con drop= False, se mantiene la dimensi??n y # el resultado ser?? una matriz
x[1,2, drop= FALSE]

#si dejamos solamente el espacio, el resultado ser?? un vector
x[1,]

#si  usamos drop= False, el resultado ser?? una matriz
x[1, ,drop= FALSE]

x<- list(aardvark=1:5)
x$a

x[["a"]]

x[["a", exact=FALSE]]

x["a"]

airquality[1:6,]
airquality[1:6,2]
airquiality[2, 1:6]

#valores faltantes
airquiality[1:6,]
completos <- complete.cases(airquality)
completos

airquality[completos,]
airquality[completos,][1:6,]

airquality[1:6,][completos,]


x<- 1:4 ; y<- 6:9
x + y
x > 2
x >= 2
x == 2
y == 8
x * y
x / y





x <- matrix(1:4,2,2); y <- matrix(rep(10,4),2,2)
x

x*y
x/y
#multiplicacion de matrices
x%%y


#8 septiembre, clases de estructuras logicco

x<- c("a","b", "c", "d")
for (i in 1:4){print(x[i])}

#version en r de: n.rows.count de vba
for(i in seq_along(x)){print(x[i])}
for(letra in x){print(letra)}
for( i in 1:4) print (x[i])

#anidar un for dentro de un for
x<- matrix(1:6,2,3)
  for  (i in seq_len(nrow(x))){
      for(j in seq_len(ncol(x))){
          print(x[i,j])
  }
}


for (i in 1:100 {})



z <- 5 
hola<- vector("numeric")
while(z>=3 && z<=10){
     print (z)
hola<- c(hola,z)
    moneda <- rbinom(1,1,0.5)
    if (moneda==1){ 
      z<- z + 1
    } else {
      z<- z - 1
    }
}

hola

plot(hola, type= "l")
plot





